# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "nokogiri", "~> 1.10"

gem "pry", "~> 0.13.1"

gem "rake", "~> 13.0"

gem "rubysl-open-uri", "~> 2.0"

gem "coderay", "~> 1.1"
