source "https://rubygems.org"

# Specify your gem's dependencies in game_release_dates.gemspec
gemspec

# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "nokogiri", "~> 1.10"

gem "rake", "~> 12.0"
